/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_meigsmart_meigrs32_util_SerialPort */

#ifndef _Included_com_meigsmart_meigrs32_util_SerialPort
#define _Included_com_meigsmart_meigrs32_util_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_meigsmart_meigrs32_util_SerialPort
 * Method:    test
 * Signature: (Ljava/lang/String;I[I[I)V
 */
JNIEXPORT void JNICALL Java_com_meigsmart_meigrs32_util_SerialPort_test
  (JNIEnv *, jobject, jstring, jint, jintArray, jintArray);

/*
 * Class:     com_meigsmart_meigrs32_util_SerialPort
 * Method:    uhf_test
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT void JNICALL Java_com_meigsmart_meigrs32_util_SerialPort_uhf_1test
  (JNIEnv *, jobject, jstring, jint, jstring);
  
/*
 * Class:     com_meigsmart_meigrs32_util_SerialPort
 * Method:    pin_test
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT void JNICALL Java_com_meigsmart_meigrs32_util_SerialPort_pin_1test
  (JNIEnv *, jobject, jstring, jint, jstring);
  

#ifdef __cplusplus
}
#endif
#endif
