/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_meigsmart_meigrs32_util_DiagJniInterface */

#ifndef _Included_com_meigsmart_meigrs32_util_DiagJniInterface
#define _Included_com_meigsmart_meigrs32_util_DiagJniInterface
#ifdef __cplusplus
extern "C" {
#endif

#define PACK_SIZE 64

typedef struct {
    uint8_t cmd_code;
    uint8_t sub_sys_id;
    uint16_t sub_sys_cmd_code;
    uint16_t ftm_cmd_id;
    uint16_t ftm_data_len;
    uint16_t ftm_rsp_pkt_size;
} __attribute__ ((packed)) ftm_header;

typedef struct {
    ftm_header sftm_header;
    uint8_t ftm_cmd_resp_result;   //0:success  1:fail 3:not test
	uint16_t size;
uint8_t Data[PACK_SIZE+4];
} __attribute__ ((packed)) ftm_cmd_response;

const int FTM_SUBCMD_BASE = 1000;
const int FTM_SUBCMD_QUERY_BASE = 3000;
const int FTM_SUBCMD_SET_RESULT_BASE = 5000;
const int FTM_SUBCMD_START = 0;
const int FTM_SUBCMD_END = 1;
const int FTM_SUBCMD_SOFTWAREINFO = 2;
const int FTM_SUBCMD_SIMCARD = 3;
const int FTM_SUBCMD_TCARD = 4;
const int FTM_SUBCMD_BLUETOOTH = 5;
const int FTM_SUBCMD_WIFI = 6;
const int FTM_SUBCMD_GPS = 7;
const int FTM_SUBCMD_GSENSOR = 8;
const int FTM_SUBCMD_COMPASS = 9;
const int FTM_SUBCMD_GYROSCOPE = 10;
const int FTM_SUBCMD_LIGHTSENSOR = 11;
const int FTM_SUBCMD_PROXIMITYSENSOR = 12;
const int FTM_SUBCMD_AIRPRESSURESENSOR = 13;
const int FTM_SUBCMD_KEYS = 14;
const int FTM_SUBCMD_HALL = 15;
const int FTM_SUBCMD_NFC = 16;
const int FTM_SUBCMD_SCANER = 17;
const int FTM_SUBCMD_SCANER_NEAR = 18;
const int FTM_SUBCMD_SCANER_FAR = 19;
const int FTM_SUBCMD_FINGERPRINT = 20;
const int FTM_SUBCMD_BATTERYCHARGER = 21;
const int FTM_SUBCMD_CTYPECOTG = 23;
const int FTM_SUBCMD_FRONTCAMERA = 24;
const int FTM_SUBCMD_BACKCAMERA = 25;
const int FTM_SUBCMD_TOUCH = 26;

const int FTM_SUBCMD_HEADSET = 100;
const int FTM_SUBCMD_HEADSETLEFTLOOP = 101;
const int FTM_SUBCMD_HEADSETRIGHTLOOP = 102;

const int FTM_SUBCMD_LCM = 120;
const int FTM_SUBCMD_BACKLIGHT150 = 121;
const int FTM_SUBCMD_BACKLIGHT100 = 122;
const int FTM_SUBCMD_BACKLIGHT50 = 123;

const int FTM_SUBCMD_LED = 130;
const int FTM_SUBCMD_LEDRED = 131;
const int FTM_SUBCMD_LEDGREEN = 132;
const int FTM_SUBCMD_LEDBLUE = 133;

const int FTM_SUBCMD_LCD = 140;
const int FTM_SUBCMD_LCDRED = 141;
const int FTM_SUBCMD_LCDGREEN = 142;
const int FTM_SUBCMD_LCDBLUE = 143;


const int FTM_SUBCMD_MAINMIC = 500;
const int FTM_SUBCMD_SUBMIC = 501;
const int FTM_SUBCMD_MICLOOP = 502;
const int FTM_SUBCMD_SPEAKER = 503;
const int FTM_SUBCMD_RECEIVER = 504;
//const int FTM_SUBCMD_CTYPECOTG = 505;
const int FTM_SUBCMD_POGOPINCHARGER2 = 506;
const int FTM_SUBCMD_POGOPINCHARGER8 = 507;
const int FTM_SUBCMD_POGOPINOTG = 508;
const int FTM_SUBCMD_BATTERYSWITCHING = 509;
const int FTM_SUBCMD_UART = 510;
const int FTM_SUBCMD_I2C = 511;
const int FTM_SUBCMD_STROBE = 512;
const int FTM_SUBCMD_VIBRATOR = 513;


const int FTM_SUBCMD_MAX = 2000;

   //1002~2000: PC send command and software can judge result by self.
    //2001~4000:PC query result
    //4001~6000: set result to software.
/*
 * Class:     com_meigsmart_meigrs32_util_DiagJniInterface
 * Method:    Diag_Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_meigsmart_meigrs32_util_DiagJniInterface_Diag_1Init
  (JNIEnv *, jobject);

/*
 * Class:     com_meigsmart_meigrs32_util_DiagJniInterface
 * Method:    Diag_Deinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_meigsmart_meigrs32_util_DiagJniInterface_Diag_1Deinit
  (JNIEnv *, jobject);

/*
 * Class:     com_meigsmart_meigrs32_util_DiagJniInterface
 * Method:    SendDiagResult
 * Signature: (IILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_meigsmart_meigrs32_util_DiagJniInterface_SendDiagResult
  (JNIEnv *, jobject, jint, jint, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
